#!/usr/bin/env expect -f

set host [lindex $argv 0]
set user [lindex $argv 1]
set pass [lindex $argv 2]
set file [lindex $argv 3]

if {$file eq ""} {
	puts "Usage : $argv0 ssh-host mysql-user mysql-pass filename"
	exit 1
}

spawn ssh $host
expect "$"
send " mysql --user=$user --password=$pass < $file \n"
send " logout\n"
expect eof
