#!/bin/bash

. enableMigrationTools

set -euo pipefail

if test "$#" -lt 2;then
    >&2 echo "Error: Usage: $0 server bases"
    exit 1;
fi

server="$1"
shift
bases="$@"

move_database "$server" $bases

while confirmDialog "Migrate some folders as well ?"
do
    move_data "$server" $bases
done
