#!/bin/bash

. enableMigrationTools

set -euo pipefail

if test "$#" -lt 2;then
    >&2 echo "Error: Usage: $0 server bases"
    exit 1;
fi

server="$1"
shift
bases="$@"

echo Migrating $bases to "$server"

move_database "$server" $bases

if confirmDialog "Migrate some folders as well? "
then

    read -p "Input some directory name to add to the list: " pluslist;
    rsync_data "$server" $bases $pluslist
fi
